/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.blog.thrift.domain;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-01-03")
public class Query implements org.apache.thrift.TBase<Query, Query._Fields>, java.io.Serializable, Cloneable, Comparable<Query> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Query");

  private static final org.apache.thrift.protocol.TField DISTINCT_FIELD_DESC = new org.apache.thrift.protocol.TField("distinct", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField FROM_TABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("fromTable", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField GROUP_BY_FIELD_DESC = new org.apache.thrift.protocol.TField("groupBy", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField HAVING_FIELD_DESC = new org.apache.thrift.protocol.TField("having", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField JOIN_FIELD_DESC = new org.apache.thrift.protocol.TField("join", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField LIMIT_FIELD_DESC = new org.apache.thrift.protocol.TField("limit", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField OFFSET_FIELD_DESC = new org.apache.thrift.protocol.TField("offset", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField ON_FIELD_DESC = new org.apache.thrift.protocol.TField("on", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField ORDER_BY_FIELD_DESC = new org.apache.thrift.protocol.TField("orderBy", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField SELECT_FIELD_DESC = new org.apache.thrift.protocol.TField("select", org.apache.thrift.protocol.TType.LIST, (short)10);
  private static final org.apache.thrift.protocol.TField UNIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("unions", org.apache.thrift.protocol.TType.LIST, (short)11);
  private static final org.apache.thrift.protocol.TField WHERE_FIELD_DESC = new org.apache.thrift.protocol.TField("where", org.apache.thrift.protocol.TType.LIST, (short)12);
  private static final org.apache.thrift.protocol.TField PARAMS_FIELD_DESC = new org.apache.thrift.protocol.TField("params", org.apache.thrift.protocol.TType.LIST, (short)13);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new QueryStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new QueryTupleSchemeFactory();

  public boolean distinct; // required
  public java.util.List<java.lang.String> fromTable; // required
  public java.util.List<java.lang.String> groupBy; // required
  public java.util.List<java.lang.String> having; // required
  public java.util.List<java.lang.String> join; // required
  public int limit; // required
  public int offset; // required
  public java.util.List<java.lang.String> on; // required
  public java.util.List<java.lang.String> orderBy; // required
  public java.util.List<java.lang.String> select; // required
  public java.util.List<java.lang.String> unions; // required
  public java.util.List<com.blog.thrift.domain.Condition> where; // required
  public java.util.List<java.lang.String> params; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DISTINCT((short)1, "distinct"),
    FROM_TABLE((short)2, "fromTable"),
    GROUP_BY((short)3, "groupBy"),
    HAVING((short)4, "having"),
    JOIN((short)5, "join"),
    LIMIT((short)6, "limit"),
    OFFSET((short)7, "offset"),
    ON((short)8, "on"),
    ORDER_BY((short)9, "orderBy"),
    SELECT((short)10, "select"),
    UNIONS((short)11, "unions"),
    WHERE((short)12, "where"),
    PARAMS((short)13, "params");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DISTINCT
          return DISTINCT;
        case 2: // FROM_TABLE
          return FROM_TABLE;
        case 3: // GROUP_BY
          return GROUP_BY;
        case 4: // HAVING
          return HAVING;
        case 5: // JOIN
          return JOIN;
        case 6: // LIMIT
          return LIMIT;
        case 7: // OFFSET
          return OFFSET;
        case 8: // ON
          return ON;
        case 9: // ORDER_BY
          return ORDER_BY;
        case 10: // SELECT
          return SELECT;
        case 11: // UNIONS
          return UNIONS;
        case 12: // WHERE
          return WHERE;
        case 13: // PARAMS
          return PARAMS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DISTINCT_ISSET_ID = 0;
  private static final int __LIMIT_ISSET_ID = 1;
  private static final int __OFFSET_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DISTINCT, new org.apache.thrift.meta_data.FieldMetaData("distinct", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FROM_TABLE, new org.apache.thrift.meta_data.FieldMetaData("fromTable", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.GROUP_BY, new org.apache.thrift.meta_data.FieldMetaData("groupBy", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.HAVING, new org.apache.thrift.meta_data.FieldMetaData("having", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.JOIN, new org.apache.thrift.meta_data.FieldMetaData("join", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.LIMIT, new org.apache.thrift.meta_data.FieldMetaData("limit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.OFFSET, new org.apache.thrift.meta_data.FieldMetaData("offset", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ON, new org.apache.thrift.meta_data.FieldMetaData("on", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ORDER_BY, new org.apache.thrift.meta_data.FieldMetaData("orderBy", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.SELECT, new org.apache.thrift.meta_data.FieldMetaData("select", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.UNIONS, new org.apache.thrift.meta_data.FieldMetaData("unions", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.WHERE, new org.apache.thrift.meta_data.FieldMetaData("where", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.blog.thrift.domain.Condition.class))));
    tmpMap.put(_Fields.PARAMS, new org.apache.thrift.meta_data.FieldMetaData("params", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Query.class, metaDataMap);
  }

  public Query() {
  }

  public Query(
    boolean distinct,
    java.util.List<java.lang.String> fromTable,
    java.util.List<java.lang.String> groupBy,
    java.util.List<java.lang.String> having,
    java.util.List<java.lang.String> join,
    int limit,
    int offset,
    java.util.List<java.lang.String> on,
    java.util.List<java.lang.String> orderBy,
    java.util.List<java.lang.String> select,
    java.util.List<java.lang.String> unions,
    java.util.List<com.blog.thrift.domain.Condition> where,
    java.util.List<java.lang.String> params)
  {
    this();
    this.distinct = distinct;
    setDistinctIsSet(true);
    this.fromTable = fromTable;
    this.groupBy = groupBy;
    this.having = having;
    this.join = join;
    this.limit = limit;
    setLimitIsSet(true);
    this.offset = offset;
    setOffsetIsSet(true);
    this.on = on;
    this.orderBy = orderBy;
    this.select = select;
    this.unions = unions;
    this.where = where;
    this.params = params;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Query(Query other) {
    __isset_bitfield = other.__isset_bitfield;
    this.distinct = other.distinct;
    if (other.isSetFromTable()) {
      java.util.List<java.lang.String> __this__fromTable = new java.util.ArrayList<java.lang.String>(other.fromTable);
      this.fromTable = __this__fromTable;
    }
    if (other.isSetGroupBy()) {
      java.util.List<java.lang.String> __this__groupBy = new java.util.ArrayList<java.lang.String>(other.groupBy);
      this.groupBy = __this__groupBy;
    }
    if (other.isSetHaving()) {
      java.util.List<java.lang.String> __this__having = new java.util.ArrayList<java.lang.String>(other.having);
      this.having = __this__having;
    }
    if (other.isSetJoin()) {
      java.util.List<java.lang.String> __this__join = new java.util.ArrayList<java.lang.String>(other.join);
      this.join = __this__join;
    }
    this.limit = other.limit;
    this.offset = other.offset;
    if (other.isSetOn()) {
      java.util.List<java.lang.String> __this__on = new java.util.ArrayList<java.lang.String>(other.on);
      this.on = __this__on;
    }
    if (other.isSetOrderBy()) {
      java.util.List<java.lang.String> __this__orderBy = new java.util.ArrayList<java.lang.String>(other.orderBy);
      this.orderBy = __this__orderBy;
    }
    if (other.isSetSelect()) {
      java.util.List<java.lang.String> __this__select = new java.util.ArrayList<java.lang.String>(other.select);
      this.select = __this__select;
    }
    if (other.isSetUnions()) {
      java.util.List<java.lang.String> __this__unions = new java.util.ArrayList<java.lang.String>(other.unions);
      this.unions = __this__unions;
    }
    if (other.isSetWhere()) {
      java.util.List<com.blog.thrift.domain.Condition> __this__where = new java.util.ArrayList<com.blog.thrift.domain.Condition>(other.where.size());
      for (com.blog.thrift.domain.Condition other_element : other.where) {
        __this__where.add(new com.blog.thrift.domain.Condition(other_element));
      }
      this.where = __this__where;
    }
    if (other.isSetParams()) {
      java.util.List<java.lang.String> __this__params = new java.util.ArrayList<java.lang.String>(other.params);
      this.params = __this__params;
    }
  }

  public Query deepCopy() {
    return new Query(this);
  }

  @Override
  public void clear() {
    setDistinctIsSet(false);
    this.distinct = false;
    this.fromTable = null;
    this.groupBy = null;
    this.having = null;
    this.join = null;
    setLimitIsSet(false);
    this.limit = 0;
    setOffsetIsSet(false);
    this.offset = 0;
    this.on = null;
    this.orderBy = null;
    this.select = null;
    this.unions = null;
    this.where = null;
    this.params = null;
  }

  public boolean isDistinct() {
    return this.distinct;
  }

  public Query setDistinct(boolean distinct) {
    this.distinct = distinct;
    setDistinctIsSet(true);
    return this;
  }

  public void unsetDistinct() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DISTINCT_ISSET_ID);
  }

  /** Returns true if field distinct is set (has been assigned a value) and false otherwise */
  public boolean isSetDistinct() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DISTINCT_ISSET_ID);
  }

  public void setDistinctIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DISTINCT_ISSET_ID, value);
  }

  public int getFromTableSize() {
    return (this.fromTable == null) ? 0 : this.fromTable.size();
  }

  public java.util.Iterator<java.lang.String> getFromTableIterator() {
    return (this.fromTable == null) ? null : this.fromTable.iterator();
  }

  public void addToFromTable(java.lang.String elem) {
    if (this.fromTable == null) {
      this.fromTable = new java.util.ArrayList<java.lang.String>();
    }
    this.fromTable.add(elem);
  }

  public java.util.List<java.lang.String> getFromTable() {
    return this.fromTable;
  }

  public Query setFromTable(java.util.List<java.lang.String> fromTable) {
    this.fromTable = fromTable;
    return this;
  }

  public void unsetFromTable() {
    this.fromTable = null;
  }

  /** Returns true if field fromTable is set (has been assigned a value) and false otherwise */
  public boolean isSetFromTable() {
    return this.fromTable != null;
  }

  public void setFromTableIsSet(boolean value) {
    if (!value) {
      this.fromTable = null;
    }
  }

  public int getGroupBySize() {
    return (this.groupBy == null) ? 0 : this.groupBy.size();
  }

  public java.util.Iterator<java.lang.String> getGroupByIterator() {
    return (this.groupBy == null) ? null : this.groupBy.iterator();
  }

  public void addToGroupBy(java.lang.String elem) {
    if (this.groupBy == null) {
      this.groupBy = new java.util.ArrayList<java.lang.String>();
    }
    this.groupBy.add(elem);
  }

  public java.util.List<java.lang.String> getGroupBy() {
    return this.groupBy;
  }

  public Query setGroupBy(java.util.List<java.lang.String> groupBy) {
    this.groupBy = groupBy;
    return this;
  }

  public void unsetGroupBy() {
    this.groupBy = null;
  }

  /** Returns true if field groupBy is set (has been assigned a value) and false otherwise */
  public boolean isSetGroupBy() {
    return this.groupBy != null;
  }

  public void setGroupByIsSet(boolean value) {
    if (!value) {
      this.groupBy = null;
    }
  }

  public int getHavingSize() {
    return (this.having == null) ? 0 : this.having.size();
  }

  public java.util.Iterator<java.lang.String> getHavingIterator() {
    return (this.having == null) ? null : this.having.iterator();
  }

  public void addToHaving(java.lang.String elem) {
    if (this.having == null) {
      this.having = new java.util.ArrayList<java.lang.String>();
    }
    this.having.add(elem);
  }

  public java.util.List<java.lang.String> getHaving() {
    return this.having;
  }

  public Query setHaving(java.util.List<java.lang.String> having) {
    this.having = having;
    return this;
  }

  public void unsetHaving() {
    this.having = null;
  }

  /** Returns true if field having is set (has been assigned a value) and false otherwise */
  public boolean isSetHaving() {
    return this.having != null;
  }

  public void setHavingIsSet(boolean value) {
    if (!value) {
      this.having = null;
    }
  }

  public int getJoinSize() {
    return (this.join == null) ? 0 : this.join.size();
  }

  public java.util.Iterator<java.lang.String> getJoinIterator() {
    return (this.join == null) ? null : this.join.iterator();
  }

  public void addToJoin(java.lang.String elem) {
    if (this.join == null) {
      this.join = new java.util.ArrayList<java.lang.String>();
    }
    this.join.add(elem);
  }

  public java.util.List<java.lang.String> getJoin() {
    return this.join;
  }

  public Query setJoin(java.util.List<java.lang.String> join) {
    this.join = join;
    return this;
  }

  public void unsetJoin() {
    this.join = null;
  }

  /** Returns true if field join is set (has been assigned a value) and false otherwise */
  public boolean isSetJoin() {
    return this.join != null;
  }

  public void setJoinIsSet(boolean value) {
    if (!value) {
      this.join = null;
    }
  }

  public int getLimit() {
    return this.limit;
  }

  public Query setLimit(int limit) {
    this.limit = limit;
    setLimitIsSet(true);
    return this;
  }

  public void unsetLimit() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LIMIT_ISSET_ID);
  }

  /** Returns true if field limit is set (has been assigned a value) and false otherwise */
  public boolean isSetLimit() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LIMIT_ISSET_ID);
  }

  public void setLimitIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LIMIT_ISSET_ID, value);
  }

  public int getOffset() {
    return this.offset;
  }

  public Query setOffset(int offset) {
    this.offset = offset;
    setOffsetIsSet(true);
    return this;
  }

  public void unsetOffset() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OFFSET_ISSET_ID);
  }

  /** Returns true if field offset is set (has been assigned a value) and false otherwise */
  public boolean isSetOffset() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OFFSET_ISSET_ID);
  }

  public void setOffsetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OFFSET_ISSET_ID, value);
  }

  public int getOnSize() {
    return (this.on == null) ? 0 : this.on.size();
  }

  public java.util.Iterator<java.lang.String> getOnIterator() {
    return (this.on == null) ? null : this.on.iterator();
  }

  public void addToOn(java.lang.String elem) {
    if (this.on == null) {
      this.on = new java.util.ArrayList<java.lang.String>();
    }
    this.on.add(elem);
  }

  public java.util.List<java.lang.String> getOn() {
    return this.on;
  }

  public Query setOn(java.util.List<java.lang.String> on) {
    this.on = on;
    return this;
  }

  public void unsetOn() {
    this.on = null;
  }

  /** Returns true if field on is set (has been assigned a value) and false otherwise */
  public boolean isSetOn() {
    return this.on != null;
  }

  public void setOnIsSet(boolean value) {
    if (!value) {
      this.on = null;
    }
  }

  public int getOrderBySize() {
    return (this.orderBy == null) ? 0 : this.orderBy.size();
  }

  public java.util.Iterator<java.lang.String> getOrderByIterator() {
    return (this.orderBy == null) ? null : this.orderBy.iterator();
  }

  public void addToOrderBy(java.lang.String elem) {
    if (this.orderBy == null) {
      this.orderBy = new java.util.ArrayList<java.lang.String>();
    }
    this.orderBy.add(elem);
  }

  public java.util.List<java.lang.String> getOrderBy() {
    return this.orderBy;
  }

  public Query setOrderBy(java.util.List<java.lang.String> orderBy) {
    this.orderBy = orderBy;
    return this;
  }

  public void unsetOrderBy() {
    this.orderBy = null;
  }

  /** Returns true if field orderBy is set (has been assigned a value) and false otherwise */
  public boolean isSetOrderBy() {
    return this.orderBy != null;
  }

  public void setOrderByIsSet(boolean value) {
    if (!value) {
      this.orderBy = null;
    }
  }

  public int getSelectSize() {
    return (this.select == null) ? 0 : this.select.size();
  }

  public java.util.Iterator<java.lang.String> getSelectIterator() {
    return (this.select == null) ? null : this.select.iterator();
  }

  public void addToSelect(java.lang.String elem) {
    if (this.select == null) {
      this.select = new java.util.ArrayList<java.lang.String>();
    }
    this.select.add(elem);
  }

  public java.util.List<java.lang.String> getSelect() {
    return this.select;
  }

  public Query setSelect(java.util.List<java.lang.String> select) {
    this.select = select;
    return this;
  }

  public void unsetSelect() {
    this.select = null;
  }

  /** Returns true if field select is set (has been assigned a value) and false otherwise */
  public boolean isSetSelect() {
    return this.select != null;
  }

  public void setSelectIsSet(boolean value) {
    if (!value) {
      this.select = null;
    }
  }

  public int getUnionsSize() {
    return (this.unions == null) ? 0 : this.unions.size();
  }

  public java.util.Iterator<java.lang.String> getUnionsIterator() {
    return (this.unions == null) ? null : this.unions.iterator();
  }

  public void addToUnions(java.lang.String elem) {
    if (this.unions == null) {
      this.unions = new java.util.ArrayList<java.lang.String>();
    }
    this.unions.add(elem);
  }

  public java.util.List<java.lang.String> getUnions() {
    return this.unions;
  }

  public Query setUnions(java.util.List<java.lang.String> unions) {
    this.unions = unions;
    return this;
  }

  public void unsetUnions() {
    this.unions = null;
  }

  /** Returns true if field unions is set (has been assigned a value) and false otherwise */
  public boolean isSetUnions() {
    return this.unions != null;
  }

  public void setUnionsIsSet(boolean value) {
    if (!value) {
      this.unions = null;
    }
  }

  public int getWhereSize() {
    return (this.where == null) ? 0 : this.where.size();
  }

  public java.util.Iterator<com.blog.thrift.domain.Condition> getWhereIterator() {
    return (this.where == null) ? null : this.where.iterator();
  }

  public void addToWhere(com.blog.thrift.domain.Condition elem) {
    if (this.where == null) {
      this.where = new java.util.ArrayList<com.blog.thrift.domain.Condition>();
    }
    this.where.add(elem);
  }

  public java.util.List<com.blog.thrift.domain.Condition> getWhere() {
    return this.where;
  }

  public Query setWhere(java.util.List<com.blog.thrift.domain.Condition> where) {
    this.where = where;
    return this;
  }

  public void unsetWhere() {
    this.where = null;
  }

  /** Returns true if field where is set (has been assigned a value) and false otherwise */
  public boolean isSetWhere() {
    return this.where != null;
  }

  public void setWhereIsSet(boolean value) {
    if (!value) {
      this.where = null;
    }
  }

  public int getParamsSize() {
    return (this.params == null) ? 0 : this.params.size();
  }

  public java.util.Iterator<java.lang.String> getParamsIterator() {
    return (this.params == null) ? null : this.params.iterator();
  }

  public void addToParams(java.lang.String elem) {
    if (this.params == null) {
      this.params = new java.util.ArrayList<java.lang.String>();
    }
    this.params.add(elem);
  }

  public java.util.List<java.lang.String> getParams() {
    return this.params;
  }

  public Query setParams(java.util.List<java.lang.String> params) {
    this.params = params;
    return this;
  }

  public void unsetParams() {
    this.params = null;
  }

  /** Returns true if field params is set (has been assigned a value) and false otherwise */
  public boolean isSetParams() {
    return this.params != null;
  }

  public void setParamsIsSet(boolean value) {
    if (!value) {
      this.params = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DISTINCT:
      if (value == null) {
        unsetDistinct();
      } else {
        setDistinct((java.lang.Boolean)value);
      }
      break;

    case FROM_TABLE:
      if (value == null) {
        unsetFromTable();
      } else {
        setFromTable((java.util.List<java.lang.String>)value);
      }
      break;

    case GROUP_BY:
      if (value == null) {
        unsetGroupBy();
      } else {
        setGroupBy((java.util.List<java.lang.String>)value);
      }
      break;

    case HAVING:
      if (value == null) {
        unsetHaving();
      } else {
        setHaving((java.util.List<java.lang.String>)value);
      }
      break;

    case JOIN:
      if (value == null) {
        unsetJoin();
      } else {
        setJoin((java.util.List<java.lang.String>)value);
      }
      break;

    case LIMIT:
      if (value == null) {
        unsetLimit();
      } else {
        setLimit((java.lang.Integer)value);
      }
      break;

    case OFFSET:
      if (value == null) {
        unsetOffset();
      } else {
        setOffset((java.lang.Integer)value);
      }
      break;

    case ON:
      if (value == null) {
        unsetOn();
      } else {
        setOn((java.util.List<java.lang.String>)value);
      }
      break;

    case ORDER_BY:
      if (value == null) {
        unsetOrderBy();
      } else {
        setOrderBy((java.util.List<java.lang.String>)value);
      }
      break;

    case SELECT:
      if (value == null) {
        unsetSelect();
      } else {
        setSelect((java.util.List<java.lang.String>)value);
      }
      break;

    case UNIONS:
      if (value == null) {
        unsetUnions();
      } else {
        setUnions((java.util.List<java.lang.String>)value);
      }
      break;

    case WHERE:
      if (value == null) {
        unsetWhere();
      } else {
        setWhere((java.util.List<com.blog.thrift.domain.Condition>)value);
      }
      break;

    case PARAMS:
      if (value == null) {
        unsetParams();
      } else {
        setParams((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DISTINCT:
      return isDistinct();

    case FROM_TABLE:
      return getFromTable();

    case GROUP_BY:
      return getGroupBy();

    case HAVING:
      return getHaving();

    case JOIN:
      return getJoin();

    case LIMIT:
      return getLimit();

    case OFFSET:
      return getOffset();

    case ON:
      return getOn();

    case ORDER_BY:
      return getOrderBy();

    case SELECT:
      return getSelect();

    case UNIONS:
      return getUnions();

    case WHERE:
      return getWhere();

    case PARAMS:
      return getParams();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DISTINCT:
      return isSetDistinct();
    case FROM_TABLE:
      return isSetFromTable();
    case GROUP_BY:
      return isSetGroupBy();
    case HAVING:
      return isSetHaving();
    case JOIN:
      return isSetJoin();
    case LIMIT:
      return isSetLimit();
    case OFFSET:
      return isSetOffset();
    case ON:
      return isSetOn();
    case ORDER_BY:
      return isSetOrderBy();
    case SELECT:
      return isSetSelect();
    case UNIONS:
      return isSetUnions();
    case WHERE:
      return isSetWhere();
    case PARAMS:
      return isSetParams();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Query)
      return this.equals((Query)that);
    return false;
  }

  public boolean equals(Query that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_distinct = true;
    boolean that_present_distinct = true;
    if (this_present_distinct || that_present_distinct) {
      if (!(this_present_distinct && that_present_distinct))
        return false;
      if (this.distinct != that.distinct)
        return false;
    }

    boolean this_present_fromTable = true && this.isSetFromTable();
    boolean that_present_fromTable = true && that.isSetFromTable();
    if (this_present_fromTable || that_present_fromTable) {
      if (!(this_present_fromTable && that_present_fromTable))
        return false;
      if (!this.fromTable.equals(that.fromTable))
        return false;
    }

    boolean this_present_groupBy = true && this.isSetGroupBy();
    boolean that_present_groupBy = true && that.isSetGroupBy();
    if (this_present_groupBy || that_present_groupBy) {
      if (!(this_present_groupBy && that_present_groupBy))
        return false;
      if (!this.groupBy.equals(that.groupBy))
        return false;
    }

    boolean this_present_having = true && this.isSetHaving();
    boolean that_present_having = true && that.isSetHaving();
    if (this_present_having || that_present_having) {
      if (!(this_present_having && that_present_having))
        return false;
      if (!this.having.equals(that.having))
        return false;
    }

    boolean this_present_join = true && this.isSetJoin();
    boolean that_present_join = true && that.isSetJoin();
    if (this_present_join || that_present_join) {
      if (!(this_present_join && that_present_join))
        return false;
      if (!this.join.equals(that.join))
        return false;
    }

    boolean this_present_limit = true;
    boolean that_present_limit = true;
    if (this_present_limit || that_present_limit) {
      if (!(this_present_limit && that_present_limit))
        return false;
      if (this.limit != that.limit)
        return false;
    }

    boolean this_present_offset = true;
    boolean that_present_offset = true;
    if (this_present_offset || that_present_offset) {
      if (!(this_present_offset && that_present_offset))
        return false;
      if (this.offset != that.offset)
        return false;
    }

    boolean this_present_on = true && this.isSetOn();
    boolean that_present_on = true && that.isSetOn();
    if (this_present_on || that_present_on) {
      if (!(this_present_on && that_present_on))
        return false;
      if (!this.on.equals(that.on))
        return false;
    }

    boolean this_present_orderBy = true && this.isSetOrderBy();
    boolean that_present_orderBy = true && that.isSetOrderBy();
    if (this_present_orderBy || that_present_orderBy) {
      if (!(this_present_orderBy && that_present_orderBy))
        return false;
      if (!this.orderBy.equals(that.orderBy))
        return false;
    }

    boolean this_present_select = true && this.isSetSelect();
    boolean that_present_select = true && that.isSetSelect();
    if (this_present_select || that_present_select) {
      if (!(this_present_select && that_present_select))
        return false;
      if (!this.select.equals(that.select))
        return false;
    }

    boolean this_present_unions = true && this.isSetUnions();
    boolean that_present_unions = true && that.isSetUnions();
    if (this_present_unions || that_present_unions) {
      if (!(this_present_unions && that_present_unions))
        return false;
      if (!this.unions.equals(that.unions))
        return false;
    }

    boolean this_present_where = true && this.isSetWhere();
    boolean that_present_where = true && that.isSetWhere();
    if (this_present_where || that_present_where) {
      if (!(this_present_where && that_present_where))
        return false;
      if (!this.where.equals(that.where))
        return false;
    }

    boolean this_present_params = true && this.isSetParams();
    boolean that_present_params = true && that.isSetParams();
    if (this_present_params || that_present_params) {
      if (!(this_present_params && that_present_params))
        return false;
      if (!this.params.equals(that.params))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((distinct) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetFromTable()) ? 131071 : 524287);
    if (isSetFromTable())
      hashCode = hashCode * 8191 + fromTable.hashCode();

    hashCode = hashCode * 8191 + ((isSetGroupBy()) ? 131071 : 524287);
    if (isSetGroupBy())
      hashCode = hashCode * 8191 + groupBy.hashCode();

    hashCode = hashCode * 8191 + ((isSetHaving()) ? 131071 : 524287);
    if (isSetHaving())
      hashCode = hashCode * 8191 + having.hashCode();

    hashCode = hashCode * 8191 + ((isSetJoin()) ? 131071 : 524287);
    if (isSetJoin())
      hashCode = hashCode * 8191 + join.hashCode();

    hashCode = hashCode * 8191 + limit;

    hashCode = hashCode * 8191 + offset;

    hashCode = hashCode * 8191 + ((isSetOn()) ? 131071 : 524287);
    if (isSetOn())
      hashCode = hashCode * 8191 + on.hashCode();

    hashCode = hashCode * 8191 + ((isSetOrderBy()) ? 131071 : 524287);
    if (isSetOrderBy())
      hashCode = hashCode * 8191 + orderBy.hashCode();

    hashCode = hashCode * 8191 + ((isSetSelect()) ? 131071 : 524287);
    if (isSetSelect())
      hashCode = hashCode * 8191 + select.hashCode();

    hashCode = hashCode * 8191 + ((isSetUnions()) ? 131071 : 524287);
    if (isSetUnions())
      hashCode = hashCode * 8191 + unions.hashCode();

    hashCode = hashCode * 8191 + ((isSetWhere()) ? 131071 : 524287);
    if (isSetWhere())
      hashCode = hashCode * 8191 + where.hashCode();

    hashCode = hashCode * 8191 + ((isSetParams()) ? 131071 : 524287);
    if (isSetParams())
      hashCode = hashCode * 8191 + params.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Query other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDistinct()).compareTo(other.isSetDistinct());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDistinct()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.distinct, other.distinct);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFromTable()).compareTo(other.isSetFromTable());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFromTable()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fromTable, other.fromTable);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGroupBy()).compareTo(other.isSetGroupBy());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroupBy()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupBy, other.groupBy);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHaving()).compareTo(other.isSetHaving());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHaving()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.having, other.having);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetJoin()).compareTo(other.isSetJoin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJoin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.join, other.join);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLimit()).compareTo(other.isSetLimit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLimit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.limit, other.limit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOffset()).compareTo(other.isSetOffset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOffset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.offset, other.offset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOn()).compareTo(other.isSetOn());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOn()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.on, other.on);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOrderBy()).compareTo(other.isSetOrderBy());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrderBy()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orderBy, other.orderBy);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSelect()).compareTo(other.isSetSelect());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSelect()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.select, other.select);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetUnions()).compareTo(other.isSetUnions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unions, other.unions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWhere()).compareTo(other.isSetWhere());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhere()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.where, other.where);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParams()).compareTo(other.isSetParams());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParams()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.params, other.params);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Query(");
    boolean first = true;

    sb.append("distinct:");
    sb.append(this.distinct);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fromTable:");
    if (this.fromTable == null) {
      sb.append("null");
    } else {
      sb.append(this.fromTable);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("groupBy:");
    if (this.groupBy == null) {
      sb.append("null");
    } else {
      sb.append(this.groupBy);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("having:");
    if (this.having == null) {
      sb.append("null");
    } else {
      sb.append(this.having);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("join:");
    if (this.join == null) {
      sb.append("null");
    } else {
      sb.append(this.join);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("limit:");
    sb.append(this.limit);
    first = false;
    if (!first) sb.append(", ");
    sb.append("offset:");
    sb.append(this.offset);
    first = false;
    if (!first) sb.append(", ");
    sb.append("on:");
    if (this.on == null) {
      sb.append("null");
    } else {
      sb.append(this.on);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("orderBy:");
    if (this.orderBy == null) {
      sb.append("null");
    } else {
      sb.append(this.orderBy);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("select:");
    if (this.select == null) {
      sb.append("null");
    } else {
      sb.append(this.select);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("unions:");
    if (this.unions == null) {
      sb.append("null");
    } else {
      sb.append(this.unions);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("where:");
    if (this.where == null) {
      sb.append("null");
    } else {
      sb.append(this.where);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("params:");
    if (this.params == null) {
      sb.append("null");
    } else {
      sb.append(this.params);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public QueryStandardScheme getScheme() {
      return new QueryStandardScheme();
    }
  }

  private static class QueryStandardScheme extends org.apache.thrift.scheme.StandardScheme<Query> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Query struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DISTINCT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.distinct = iprot.readBool();
              struct.setDistinctIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FROM_TABLE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.fromTable = new java.util.ArrayList<java.lang.String>(_list0.size);
                java.lang.String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.fromTable.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setFromTableIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // GROUP_BY
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.groupBy = new java.util.ArrayList<java.lang.String>(_list3.size);
                java.lang.String _elem4;
                for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                {
                  _elem4 = iprot.readString();
                  struct.groupBy.add(_elem4);
                }
                iprot.readListEnd();
              }
              struct.setGroupByIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HAVING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                struct.having = new java.util.ArrayList<java.lang.String>(_list6.size);
                java.lang.String _elem7;
                for (int _i8 = 0; _i8 < _list6.size; ++_i8)
                {
                  _elem7 = iprot.readString();
                  struct.having.add(_elem7);
                }
                iprot.readListEnd();
              }
              struct.setHavingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // JOIN
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                struct.join = new java.util.ArrayList<java.lang.String>(_list9.size);
                java.lang.String _elem10;
                for (int _i11 = 0; _i11 < _list9.size; ++_i11)
                {
                  _elem10 = iprot.readString();
                  struct.join.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setJoinIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LIMIT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.limit = iprot.readI32();
              struct.setLimitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // OFFSET
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.offset = iprot.readI32();
              struct.setOffsetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // ON
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list12 = iprot.readListBegin();
                struct.on = new java.util.ArrayList<java.lang.String>(_list12.size);
                java.lang.String _elem13;
                for (int _i14 = 0; _i14 < _list12.size; ++_i14)
                {
                  _elem13 = iprot.readString();
                  struct.on.add(_elem13);
                }
                iprot.readListEnd();
              }
              struct.setOnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ORDER_BY
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list15 = iprot.readListBegin();
                struct.orderBy = new java.util.ArrayList<java.lang.String>(_list15.size);
                java.lang.String _elem16;
                for (int _i17 = 0; _i17 < _list15.size; ++_i17)
                {
                  _elem16 = iprot.readString();
                  struct.orderBy.add(_elem16);
                }
                iprot.readListEnd();
              }
              struct.setOrderByIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SELECT
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list18 = iprot.readListBegin();
                struct.select = new java.util.ArrayList<java.lang.String>(_list18.size);
                java.lang.String _elem19;
                for (int _i20 = 0; _i20 < _list18.size; ++_i20)
                {
                  _elem19 = iprot.readString();
                  struct.select.add(_elem19);
                }
                iprot.readListEnd();
              }
              struct.setSelectIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // UNIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list21 = iprot.readListBegin();
                struct.unions = new java.util.ArrayList<java.lang.String>(_list21.size);
                java.lang.String _elem22;
                for (int _i23 = 0; _i23 < _list21.size; ++_i23)
                {
                  _elem22 = iprot.readString();
                  struct.unions.add(_elem22);
                }
                iprot.readListEnd();
              }
              struct.setUnionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // WHERE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.where = new java.util.ArrayList<com.blog.thrift.domain.Condition>(_list24.size);
                com.blog.thrift.domain.Condition _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = new com.blog.thrift.domain.Condition();
                  _elem25.read(iprot);
                  struct.where.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setWhereIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // PARAMS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list27 = iprot.readListBegin();
                struct.params = new java.util.ArrayList<java.lang.String>(_list27.size);
                java.lang.String _elem28;
                for (int _i29 = 0; _i29 < _list27.size; ++_i29)
                {
                  _elem28 = iprot.readString();
                  struct.params.add(_elem28);
                }
                iprot.readListEnd();
              }
              struct.setParamsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Query struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(DISTINCT_FIELD_DESC);
      oprot.writeBool(struct.distinct);
      oprot.writeFieldEnd();
      if (struct.fromTable != null) {
        oprot.writeFieldBegin(FROM_TABLE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.fromTable.size()));
          for (java.lang.String _iter30 : struct.fromTable)
          {
            oprot.writeString(_iter30);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.groupBy != null) {
        oprot.writeFieldBegin(GROUP_BY_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.groupBy.size()));
          for (java.lang.String _iter31 : struct.groupBy)
          {
            oprot.writeString(_iter31);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.having != null) {
        oprot.writeFieldBegin(HAVING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.having.size()));
          for (java.lang.String _iter32 : struct.having)
          {
            oprot.writeString(_iter32);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.join != null) {
        oprot.writeFieldBegin(JOIN_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.join.size()));
          for (java.lang.String _iter33 : struct.join)
          {
            oprot.writeString(_iter33);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LIMIT_FIELD_DESC);
      oprot.writeI32(struct.limit);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(OFFSET_FIELD_DESC);
      oprot.writeI32(struct.offset);
      oprot.writeFieldEnd();
      if (struct.on != null) {
        oprot.writeFieldBegin(ON_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.on.size()));
          for (java.lang.String _iter34 : struct.on)
          {
            oprot.writeString(_iter34);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.orderBy != null) {
        oprot.writeFieldBegin(ORDER_BY_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.orderBy.size()));
          for (java.lang.String _iter35 : struct.orderBy)
          {
            oprot.writeString(_iter35);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.select != null) {
        oprot.writeFieldBegin(SELECT_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.select.size()));
          for (java.lang.String _iter36 : struct.select)
          {
            oprot.writeString(_iter36);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.unions != null) {
        oprot.writeFieldBegin(UNIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.unions.size()));
          for (java.lang.String _iter37 : struct.unions)
          {
            oprot.writeString(_iter37);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.where != null) {
        oprot.writeFieldBegin(WHERE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.where.size()));
          for (com.blog.thrift.domain.Condition _iter38 : struct.where)
          {
            _iter38.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.params != null) {
        oprot.writeFieldBegin(PARAMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.params.size()));
          for (java.lang.String _iter39 : struct.params)
          {
            oprot.writeString(_iter39);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public QueryTupleScheme getScheme() {
      return new QueryTupleScheme();
    }
  }

  private static class QueryTupleScheme extends org.apache.thrift.scheme.TupleScheme<Query> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Query struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDistinct()) {
        optionals.set(0);
      }
      if (struct.isSetFromTable()) {
        optionals.set(1);
      }
      if (struct.isSetGroupBy()) {
        optionals.set(2);
      }
      if (struct.isSetHaving()) {
        optionals.set(3);
      }
      if (struct.isSetJoin()) {
        optionals.set(4);
      }
      if (struct.isSetLimit()) {
        optionals.set(5);
      }
      if (struct.isSetOffset()) {
        optionals.set(6);
      }
      if (struct.isSetOn()) {
        optionals.set(7);
      }
      if (struct.isSetOrderBy()) {
        optionals.set(8);
      }
      if (struct.isSetSelect()) {
        optionals.set(9);
      }
      if (struct.isSetUnions()) {
        optionals.set(10);
      }
      if (struct.isSetWhere()) {
        optionals.set(11);
      }
      if (struct.isSetParams()) {
        optionals.set(12);
      }
      oprot.writeBitSet(optionals, 13);
      if (struct.isSetDistinct()) {
        oprot.writeBool(struct.distinct);
      }
      if (struct.isSetFromTable()) {
        {
          oprot.writeI32(struct.fromTable.size());
          for (java.lang.String _iter40 : struct.fromTable)
          {
            oprot.writeString(_iter40);
          }
        }
      }
      if (struct.isSetGroupBy()) {
        {
          oprot.writeI32(struct.groupBy.size());
          for (java.lang.String _iter41 : struct.groupBy)
          {
            oprot.writeString(_iter41);
          }
        }
      }
      if (struct.isSetHaving()) {
        {
          oprot.writeI32(struct.having.size());
          for (java.lang.String _iter42 : struct.having)
          {
            oprot.writeString(_iter42);
          }
        }
      }
      if (struct.isSetJoin()) {
        {
          oprot.writeI32(struct.join.size());
          for (java.lang.String _iter43 : struct.join)
          {
            oprot.writeString(_iter43);
          }
        }
      }
      if (struct.isSetLimit()) {
        oprot.writeI32(struct.limit);
      }
      if (struct.isSetOffset()) {
        oprot.writeI32(struct.offset);
      }
      if (struct.isSetOn()) {
        {
          oprot.writeI32(struct.on.size());
          for (java.lang.String _iter44 : struct.on)
          {
            oprot.writeString(_iter44);
          }
        }
      }
      if (struct.isSetOrderBy()) {
        {
          oprot.writeI32(struct.orderBy.size());
          for (java.lang.String _iter45 : struct.orderBy)
          {
            oprot.writeString(_iter45);
          }
        }
      }
      if (struct.isSetSelect()) {
        {
          oprot.writeI32(struct.select.size());
          for (java.lang.String _iter46 : struct.select)
          {
            oprot.writeString(_iter46);
          }
        }
      }
      if (struct.isSetUnions()) {
        {
          oprot.writeI32(struct.unions.size());
          for (java.lang.String _iter47 : struct.unions)
          {
            oprot.writeString(_iter47);
          }
        }
      }
      if (struct.isSetWhere()) {
        {
          oprot.writeI32(struct.where.size());
          for (com.blog.thrift.domain.Condition _iter48 : struct.where)
          {
            _iter48.write(oprot);
          }
        }
      }
      if (struct.isSetParams()) {
        {
          oprot.writeI32(struct.params.size());
          for (java.lang.String _iter49 : struct.params)
          {
            oprot.writeString(_iter49);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Query struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(13);
      if (incoming.get(0)) {
        struct.distinct = iprot.readBool();
        struct.setDistinctIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list50 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.fromTable = new java.util.ArrayList<java.lang.String>(_list50.size);
          java.lang.String _elem51;
          for (int _i52 = 0; _i52 < _list50.size; ++_i52)
          {
            _elem51 = iprot.readString();
            struct.fromTable.add(_elem51);
          }
        }
        struct.setFromTableIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list53 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.groupBy = new java.util.ArrayList<java.lang.String>(_list53.size);
          java.lang.String _elem54;
          for (int _i55 = 0; _i55 < _list53.size; ++_i55)
          {
            _elem54 = iprot.readString();
            struct.groupBy.add(_elem54);
          }
        }
        struct.setGroupByIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list56 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.having = new java.util.ArrayList<java.lang.String>(_list56.size);
          java.lang.String _elem57;
          for (int _i58 = 0; _i58 < _list56.size; ++_i58)
          {
            _elem57 = iprot.readString();
            struct.having.add(_elem57);
          }
        }
        struct.setHavingIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list59 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.join = new java.util.ArrayList<java.lang.String>(_list59.size);
          java.lang.String _elem60;
          for (int _i61 = 0; _i61 < _list59.size; ++_i61)
          {
            _elem60 = iprot.readString();
            struct.join.add(_elem60);
          }
        }
        struct.setJoinIsSet(true);
      }
      if (incoming.get(5)) {
        struct.limit = iprot.readI32();
        struct.setLimitIsSet(true);
      }
      if (incoming.get(6)) {
        struct.offset = iprot.readI32();
        struct.setOffsetIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list62 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.on = new java.util.ArrayList<java.lang.String>(_list62.size);
          java.lang.String _elem63;
          for (int _i64 = 0; _i64 < _list62.size; ++_i64)
          {
            _elem63 = iprot.readString();
            struct.on.add(_elem63);
          }
        }
        struct.setOnIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TList _list65 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.orderBy = new java.util.ArrayList<java.lang.String>(_list65.size);
          java.lang.String _elem66;
          for (int _i67 = 0; _i67 < _list65.size; ++_i67)
          {
            _elem66 = iprot.readString();
            struct.orderBy.add(_elem66);
          }
        }
        struct.setOrderByIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TList _list68 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.select = new java.util.ArrayList<java.lang.String>(_list68.size);
          java.lang.String _elem69;
          for (int _i70 = 0; _i70 < _list68.size; ++_i70)
          {
            _elem69 = iprot.readString();
            struct.select.add(_elem69);
          }
        }
        struct.setSelectIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TList _list71 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.unions = new java.util.ArrayList<java.lang.String>(_list71.size);
          java.lang.String _elem72;
          for (int _i73 = 0; _i73 < _list71.size; ++_i73)
          {
            _elem72 = iprot.readString();
            struct.unions.add(_elem72);
          }
        }
        struct.setUnionsIsSet(true);
      }
      if (incoming.get(11)) {
        {
          org.apache.thrift.protocol.TList _list74 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.where = new java.util.ArrayList<com.blog.thrift.domain.Condition>(_list74.size);
          com.blog.thrift.domain.Condition _elem75;
          for (int _i76 = 0; _i76 < _list74.size; ++_i76)
          {
            _elem75 = new com.blog.thrift.domain.Condition();
            _elem75.read(iprot);
            struct.where.add(_elem75);
          }
        }
        struct.setWhereIsSet(true);
      }
      if (incoming.get(12)) {
        {
          org.apache.thrift.protocol.TList _list77 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.params = new java.util.ArrayList<java.lang.String>(_list77.size);
          java.lang.String _elem78;
          for (int _i79 = 0; _i79 < _list77.size; ++_i79)
          {
            _elem78 = iprot.readString();
            struct.params.add(_elem78);
          }
        }
        struct.setParamsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

